name: scipy2018-swe
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py36_0
  - atomicwrites=1.1.5=py36_0
  - attrs=18.1.0=py_1
  - backcall=0.1.0=py_0
  - bleach=2.1.3=py_0
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - decorator=4.3.0=py_0
  - entrypoints=0.2.3=py36_1
  - html5lib=1.0.1=py_0
  - icu=58.2=0
  - ipdb=0.11=py36_0
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.2.1=py36_1
  - jedi=0.12.0=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=2
  - jsonschema=2.6.0=py36_1
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_0
  - jupyter_core=4.4.0=py_0
  - libpng=1.6.34=0
  - libsodium=1.0.16=0
  - markupsafe=1.0=py36_0
  - mistune=0.8.3=py36_1
  - more-itertools=4.2.0=py_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - ncurses=5.9=10
  - notebook=5.5.0=py36_0
  - openssl=1.0.2o=0
  - pandoc=2.2.1=hde52d81_0
  - pandocfilters=1.4.2=py36_0
  - parso=0.2.1=py_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pip=9.0.3=py36_0
  - pluggy=0.6.0=py_0
  - prompt_toolkit=1.0.15=py36_0
  - ptyprocess=0.5.2=py36_0
  - py=1.5.3=py_0
  - pygments=2.2.0=py36_0
  - pyqt=5.6.0=py36_5
  - pytest=3.6.1=py36_0
  - python=3.6.5=1
  - python-dateutil=2.7.3=py_0
  - pyzmq=17.0.0=py36_4
  - qt=5.6.2=h9e3eb04_4
  - qtconsole=4.3.1=py36_0
  - readline=7.0=0
  - send2trash=1.5.0=py_0
  - setuptools=39.2.0=py36_0
  - simplegeneric=0.8.1=py36_0
  - sip=4.18=py36_1
  - six=1.11.0=py36_1
  - sqlite=3.20.1=2
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - tk=8.6.7=0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_0
  - wheel=0.31.0=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - xz=5.2.3=0
  - zeromq=4.2.5=1
  - zlib=1.2.11=h470a237_3
  - snakeviz=0.4.2=py36h2529b96_0
prefix: /Users/mattdavis/miniconda3/envs/scipy2018-swe

